Review form feature
a-osm/Berry-Tales pull request #5
Opened 2022-05-19 21:28 UTC by a-osm

2022-05-19 22:02 UTC, safang99 requested changes
Nice job getting a big feature up and functional! The next step is going to be adding in front end and backend validation before getting this merged.  Take your time as you go through to address the comments and click `resolve` on each comment as you go, so it's easy to keep track of what you have done already

2022-05-19 22:02 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +      const response = await fetch(`/api/v1/berries/${berryId}/reviews`, {
Since we already have the `berryId` attached to the payload, we can rename our endpoint to POST to `/api/v1/reviews`

2022-05-19 22:02 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +  }
Let's also add some front end validation for any required fields to make sure they are valid before calling `addReview`.  We can create a `validForSubmission()` function and use that to determine if we will send the POST request or display errors and remain on the page.

```js
  const handleSubmit = event => {
    event.preventDefault()
    if (validForSubmission()) {
      addReview(formPayload)
    }
  }
```

2022-05-19 22:02 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +      <h1>Add a review to this berry!</h1>
Instead of saying "this berry" let's display the actual name

2022-05-19 22:02 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +      <Link to={"/berries"}>Back to berries</Link>
A `Link` back to this berry show page would also be great since that is how the user got here

2022-05-19 22:02 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +            max="5"
Love it!

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/controllers/ReviewsApiV1Controller.java
> +//     Optional<Berry> berry = berryService.findById(Long.valueOf(id));
Commented out code that looks like it can now be removed after refactoring to use a Form Model 👍

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/controllers/ReviewsApiV1Controller.java
> +@RequestMapping("api/v1/berries/{id}/reviews")
After we update the fetch we can also change this to just be `/api/v1/reviews`

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/controllers/ReviewsApiV1Controller.java
> +  public ResponseEntity<Map<String, Review>> create(@PathVariable Integer id, @RequestBody ReviewForm reviewForm){
Then we can remove `@Pathvariable Integer id` and be sure to include `@Valid` for validation and `BindingResult` to catch those errors.  Then add in handling for those model level errors

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/models/Review.java
> +  private String name;
Since this is `NOT NULL` on the database level, we should include a `@NotBlank` or `@NotNull` annotation depending on what we want to validate against

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/seeders/ReviewSeeder.java
> +    }
No rating from Shaq?

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/services/ReviewDatabaseService.java
> +    this.berriesRepository = berriesRepository;
It doesn't look like `berriesRepository` is being used here, so let's remove the field and remove it from the constructor

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/services/ReviewDatabaseService.java
> +    Optional<Berry> berry = berryService.findById(Long.valueOf(reviewForm.getBerryId()));
Instead of having to cast the `getBerryId()` to a Long, let's just change it to a Long on the Form Model

2022-05-19 22:02 UTC, safang99 commented on src/main/java/com/launchacademy/reviews/models/ReviewForm.java
> +  private Integer berryId;
Make this a Long if you are using BIG SERIAL for that table

2022-05-20 15:17 UTC, a-osm commented on src/main/frontend/client/components/NewReviewForm.js
> +      const response = await fetch(`/api/v1/berries/${berryId}/reviews`, {
We tried this and our post request failed :(

2022-05-20 17:14 UTC, RockyCifu commented on src/main/frontend/client/assets/scss/main.scss
>  *::after {
This is also a great place to reset the default margins and padding to 0 so you can be more consistent across browsers.

2022-05-20 17:15 UTC, RockyCifu commented on src/main/frontend/client/components/App.js
> +
Lots of extra spacing here.

2022-05-20 17:21 UTC, RockyCifu commented on src/main/frontend/client/components/NewReviewForm.js
> +      const response = await fetch(`/api/v1/berries/${berryId}/reviews`, {
You will need two controllers to handle for this. `BerriesApiV1Controller` and `ReviewsApiV1Controller` one will handle `/api/v1/berries` and the other will handle for `/api/v1/reviews`

2022-05-20 17:26 UTC, RockyCifu commented on src/main/java/com/launchacademy/reviews/models/ReviewForm.java
> +  @NotNull
@NotNull will allow an empty string. Switch this to @NotBlank

2022-05-20 17:29 UTC, RockyCifu commented on src/main/java/com/launchacademy/reviews/services/ReviewDatabaseService.java
> +  public Review createReview(ReviewForm reviewForm) {
We need some backend validation here.

2022-05-20 17:31 UTC, RockyCifu requested changes
Hey all! Great work on this feature! There needs to be some backend validation for the review submission and the api route for review is not set up correctly. Please reach out if you have any questions.

2022-05-20 19:47 UTC, safang99 requested changes
1 typo and 1 formatting fix and then it looks good to me

2022-05-20 19:47 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +      const response = await fetch(`/api/v1//reviews`, {
Looks like an extra "/" after `v1`

2022-05-20 19:47 UTC, safang99 commented on src/main/frontend/client/components/NewReviewForm.js
> +  return (
extra empty line we can remove here

2022-05-20 19:57 UTC, merged